apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: app2
  name: app2
  namespace: roshan
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app2

  template:
    metadata:

      labels:
        app: app2
    spec:
      containers:
      - image: nginx
        name: nginx


