apiVersion: v1
kind: Pod
metadata:
 name: emptydirpod
 namespace: roshan
 labels:
   app: empty
spec:
 volumes:
 - name: roshvol
   emptyDir: {}
 containers:
 - image: nginx
   name: mynginx
   volumeMounts:
   - name: roshvol
     mountPath: /usr/share/nginx/html/
 - image: alpine
   name: alpinecont
   volumeMounts:
   - name: roshvol
     mountPath: /code
   command: ["/bin/sh"]
   args: ["-c", "ping 8.8.8.8 > /code/index.html" ]

